module.exports = {
    "id": "zqyd",
    "name": "钟情阅读",
    "keys": ["zqydbody","zqydbody2",],
    "author": "@tom",
    "settings": [{
      "id": "zqydSuffix",
      "name": "当前账号",
      "val": "1",
      "type": "number",
      "desc": "当前抓取ck记录的账号序号，如：1、2、3、4"
    }, {
      "id": "zqydCount",
      "name": "账号个数",
      "val": "1",
      "type": "number",
      "desc": "指定任务最多跑几个账号，根据抓取的账号数据个数来设值"
    }, {
      "id": "zqydXH",
      "name": "循环获取ck",
      "val": "0",
      "type": "number",
      "desc": "0关闭，1打开，默认关闭"
    }, {
      "id": "zqydTXTX",
      "name": "txtx",
      "val": "0",
      "type": "number",
      "desc": "0关闭，1打开，默认关闭"
    }, {
      "id": "zqydSC",
      "name": "sc",
      "val": "0",
      "type": "number",
      "desc": "0关闭，1打开，默认关闭"
    }, {
      "id": "zqydnotifyttt",
      "name": "推送控制",
      "val": "1",
      "type": "number",
      "desc": "0关闭，1推送,默认12点以及23点推送"
    }, {
      "id": "zqydnotifyInterval",
      "name": "通知控制",
      "val": "2",
      "type": "number",
      "desc": "0关闭，1为 所有通知，2为 12，23 点通知，3为 6，12，18，23 点通知"
    }, {
      "id": "zqydMinutes",
      "name": "推送-通知 分钟控制",
      "val": "10",
      "type": "number",
      "desc": "推送以及通知控制在什么分钟段，可设置0-59,默认0到10"
    }],
    "repo": "https://gitee.com/tom210120/tom/raw/master/ZQ/zq.js",
    "icons": ["https://gitee.com/tom210120/tom/raw/master/Tom/Tom.jpg", "https://gitee.com/tom210120/tom/raw/master/Tom/Tom.jpg"],
    "script": "https://gitee.com/tom210120/tom/raw/master/ZQ/zq.js",
    "icon": "https://gitee.com/tom210120/tom/raw/master/Tom/Tom.jpg",
    "favIcon": "mdi-star-outline",
    "favIconColor": "grey",
    "datas": [{
      "key": "zqydbody",
      "val": "p=wXPkPrW1Kghg%3DsgIQMIWD99JWTlyj3kDM8CBKkh1quTk1Cqk9FdzMw9mhmjFeeRN9CqqmA_NB2lYk4hCYL6gfmyAxt90qoCU3ObHnFidvoEEacdftdKTPwRkLrpgwe6S-pZXSC6Pc2CL0crQ8agGxeszORYnc7lTgor7Hs40Zd7krUUrevLd11i0Wncoeb0KAeuOrvcGAVBXtAi9C2tOoNQrexTxDezJq6fW7TNLM-JyQ3UG0MCpCVOJNf9SQFen258XykuUlt-04go-g29GrUFmw6ITPCxCZvVB6cVZ9TGGn7Lj7Kc7BPkm7mWdHG4qVLRO6JogzXeVROf9_2tKBr3wodoiyZm_7wvfPBpqF8M79jAe0-cewdPB9QlY0-n7YoofdMBw52ZZ2J_QzjGm_MWiVipNGEXuudedR9Yuxd2KsqzuGcr7XJNPhzDXveTewfRetkDG0Uq6I3HudgY4iWiStMxB3m3qIkAJQCZq9ILxlNYIUj5_YfnmxcjDx_Nb-01MnbOp-9YyYksmPKAjpcfWqU4t_lv4QqifhOTF01IB2QrqXZt47Mjh0_CtMDXoErx6Oz9D953qvw6iZVJ85hWJDyRJ3w60JFZZidcF6DBeApXRoNb_7X38FvepOrf-lHpM2Mh4meTJKAbb4yYETLjdgo2sQ6uv5vfeMEUEp5MpvdiE9n_5LWM3qebd6pchVcuiB0otlJ3vHAevvWNPq62wukoKn-9fx00nM9RgZJof-tqyR_tx11VvagOS0PafVujfaB1mcvzs_CJbPoq2QAioI2ZSzskgJfbqfqWvdN1fiaXd8d_47gifkHbq4BbLAQeakbFw7AzD-lQAZEijwdOcrtGuCwomtXQFXtYjpb6vFyGSx6NCew-e8Gy60F1DOpPhKQNkPVCsm69Tq_9vqrhbjRXUPFMlg9cU3KAS9vGwAPjX0znTDvY_vXLHdswmyuf63A4oD9O2KASTRXmubCUYBvhghZh0uhZn9A8L0nYT4B-8ZZwcQyT7VsppZWcwuwKGcMrUB2idk5Yftk3qG6bUxZ0vFsuAC_BMRgmxDscy7v_e8JulRuyuFuyyECezQOp1KRMqFjB3BIYLruK8G69VyxE1wGcmfmzwqCrwFmBWzcTN3u6J4lDYVE8gJPNYOE0rW7LZjRm2h88xYB3czEP_rjXV4wDfkXA2thfgbSbKsV_KfzT6Ar4Kyxb_N5A-SFl_LRT-GmGdX"
    }, {
      "key": "zqydbody2",
      "val": "12345678"
    }, {
      "key": "zqydbody3",
      "val": "1111111"
    }, {
      "key": "zqydbody4",
      "val": "22222222"
    }, {
      "key": "zqydbody5",
      "val": "33333333"
    }, {
      "key": "zqydbody6",
      "val": "44444444"
    }, {
      "key": "zqydbody7",
      "val": "55555555"
    }],
    "sessions": [],
    "isLoaded": true
  }
