name: zzk

on:
  workflow_dispatch:
  schedule:
    - cron: 7 8,11 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zqydbody: ${{ secrets.ZQYDBODY }}
        zqydbody2: ${{ secrets.ZQYDBODY2 }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【zqkkhear】'
        if: env.zqydbody
        run: |
          node zqkkhear.js
        
         
      - name: '运行 【zqkkhear二】'
        if: env.zqydbody2
        run: |
          node zqkkhear.js
       
    
